cp crd/output/yaml/Agent.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/AuditContext.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/CloudAccount.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/ContainerStatus.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Deployment.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/DeploymentVersion.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Domain.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Group.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Gvc.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Identity.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Image.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/IpSet.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/JobExecutionStatus.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Location.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Mk8sCluster.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Policy.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Secret.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/ServiceAccount.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/User.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/VolumeSet.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/VolumeSetStatusLocation.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/PersistentVolumeStatus.yaml ../k8s-operator/chart/templates/crd
cp crd/output/yaml/Workload.yaml ../k8s-operator/chart/templates/crd